trigger:
  branches:
    include:
      - main  # Adjust if using a different branch

pool:
  vmImage: 'windows-latest'

variables:
  appName: 'MyMvcApp'  # Change this to your App Service name
  resourceGroup: 'MyResourceGroup'
  serviceConnection: 'AzureAppServiceConnection'

steps:
  - task: UseDotNet@2
    displayName: 'Install .NET SDK'
    inputs:
      packageType: 'sdk'
      version: '9.0.102'  # Change based on your .NET version
      installationPath: $(Agent.ToolsDirectory)/dotnet

  - task: NuGetCommand@2
    displayName: 'Restore NuGet Packages'
    inputs:
      restoreSolution: '**/*.sln'

  - task: VSBuild@1
    displayName: 'Build Solution'
    inputs:
      solution: '**/*.sln'
      platform: 'Any CPU'
      configuration: 'Release'

  - task: VSTest@2
    displayName: 'Run Unit Tests'
    inputs:
      testSelector: 'testAssemblies'
      testAssemblyVer2: '**\$(buildConfiguration)\**\*test*.dll'
      searchFolder: '$(System.DefaultWorkingDirectory)'

  - task: ArchiveFiles@2
    displayName: 'Create ZIP Package'
    inputs:
      rootFolderOrFile: '$(Build.ArtifactStagingDirectory)'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/app.zip'
      replaceExistingArchive: true

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Build Artifacts'
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)/app.zip'
      artifactName: 'drop'
  
  - task: DownloadBuildArtifacts@0
    displayName: 'Download Build Artifact'
    inputs:
      buildType: 'current'
      artifactName: 'drop'
      downloadPath: '$(Pipeline.Workspace)'

  - task: AzureRmWebAppDeployment@4
    displayName: 'Deploy to Azure App Service'
    inputs:
      ConnectionType: 'AzureRM'
      azureSubscription: $(serviceConnection)
      appType: 'webApp'
      WebAppName: $(appName)
      package: '$(Pipeline.Workspace)/drop/app.zip'
